### ISSUE TITLE
Considering using DefaultAWSCredentialsProviderChain

### ISSUE THREAD

**Issue by efenderbosch** [j256/cloudwatch-logback-appender#1]
I'm just looking at several of the Logback appenders for CloudWatch and noticed you require that the key and secret be in ``logback.xml`` and use ``BasicAWSCredentials``. If you switched to ``DefaultAWSCredentialsProviderChain`` then users could inject their credentials several different ways (env var, sys props, .aws/credentials, ec2 container creds) w/o having to check them in their VCS.

**Comment by j256** [comment]
Good point Eric.  So I just need to do something like the following?

			AWSCredentials awsCredentials;
			if (accessKey == null) {
				awsCredentials = new DefaultAWSCredentialsProviderChain().getCredentials();
			} else {
				awsCredentials = new BasicAWSCredentials(accessKey, secretKey);
			}

**Comment by j256** [comment]
Ok fixed.  Seems to work.  Thanks again for the suggestion.
