### ISSUE TITLE
Question: Contention with jasypt-spring-boot when running Spring Boot app as executable jar?

### ISSUE THREAD

**Issue by curtistee** [j256/cloudwatch-logback-appender#11]
Have you guys ever run into this? Running this app in an IDE works like a champ. However, when running the app as an executable jar from the CLI it shuts down as soon as the logback code is hit _with no errors._ Commenting out the cloudwatch appender definitions & references in logback-spring.xml works, as does not instantiating the StandardEncryptableEnvironment in the main method of the SpringApplication class. Obviously neither solution is workable :( 

Here's our main class:

```java
package com.somepackagename;

import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;

import com.ulisesbocchio.jasyptspringboot.environment.StandardEncryptableEnvironment;

@SpringBootApplication
public class MyApplication {

    public static void main(String... args) {
    
        new SpringApplicationBuilder()
                .environment(new StandardEncryptableEnvironment())
                .sources(MyApplication.class).run(args);
        
    }
}
```

We're using v1.10 of your appender and Logback with slf4j v1.7.12. It is perfectly happy with our configuration, and our test cases all pass with flying colors. Let me know if you've run across this issue or have any ideas. Thanks!

**Comment by curtistee** [comment]
Addendum: We're encrypting our AWS credentials using the jasypt-spring-boot stuff & have those defined in our application.yaml file. In our logback-spring.xml file they are referenced & defined as local properties like this:

```xml
<springProperty name="awsAccessKeyId" source="cloudwatchappender.aws.accessKeyId"/>
<springProperty name="awsSecretKey" source="cloudwatchappender.aws.secretKey" />
```

The decryption is _supposed_ to happen before the logging environment is initialized, but it may not be; that may be what's causing the failure. Without any sort of error-reporting from the cloudwatch appender it's difficult to tell.

**Comment by j256** [comment]
I'm not sure but maybe you are confusing a spring property with a Java system property?  The docs talk about system properties which need to be set with -D or with `System.setProperty(...)`.  See: https://github.com/j256/cloudwatch-logback-appender#aws-permissions

**Comment by j256** [comment]
> Without any sort of error-reporting from the cloudwatch appender it's difficult to tell.

The appender does write errors to the logs but if you don't configure an emergency appender, I'm not sure what it should be doing.  I don't think it should be writing to stderr.

Thoughts?

**Comment by curtistee** [comment]
Thanks for the replies, Gray (and the great work BTW). 

Agreed re: stderr. If anything it seems there's an error condition which only surfaces under these conditions.

For giggles & grins, I created a minimal Spring boot app with `spring-boot-starter-webservices` and Ulises Bocchio's `jasypt-spring-boot-starter`, along with your appender. Sure enough it started fine & dandy in IntelliJ, but stopped at the same point when running from the CLI.

As you can see from the log, no complaints whatsoever from the appender configuration-wise, nor from LogBack. So the questions would be:

1. What in the appender code might cause the app to shut down this early and,
2. Why does it run fine in the IDE but not as an executable JAR from the CLI?

I'll keep digging into this, as I think it's worth the effort. Note I've forked your repo, so I won't break anything. Thanks again for the replies.

**Comment by j256** [comment]
Geez.  I'd really be surprised if the appender causes your application to "shut down" which I guess means exit.  That really sound like something else.  Are you configuring an emergency appender?

In terms of why it runs in the IDE but not as a jar, there are a bunch of differences of course.  It depends on classpath, properties, how the jar was built, etc...

**Comment by RedXi** [comment]
We were facing exactly the same problem here after updating spring-boot-starter-parent from version 1.5.8.RELEASE to 1.5.10.RELEASE

We were discovering exactly the same behavior if (and only if) CloudWatchAppender was used as appender. I tried setting the root logger to TRACE and used CloudWatchAppender and ConsoleAppender simultaneously. At a first glance it looked as if the application got stuck in an infinite loop during startup.

**Comment by j256** [comment]
Any other details @RedXi ?  I try to delay the AWS configuration but maybe I'm wiring something up too early?

**Comment by RedXi** [comment]
I gave it another try with the most recent version of spring boot starter (2.0.1.RELEASE) - and it works flawlessly now!

Maybe this is (now) a solution for the original issue as well.

**Comment by j256** [comment]
I'm going to close this for now but feel to reopen if it reoccurs.
