### ISSUE TITLE
selectively import aws sdk dependencies instead of full one

### ISSUE THREAD

**Issue by m1schka** [j256/cloudwatch-logback-appender#12]
hey.
I've been using your project. in my dependencies, besides your package, I also needes the aws sdk. Since I didn't want to import the full sdk (which adds almost 100MB to the output jar), I've figured out which parts of the sdk you use. following the aws sdk instructions, I ended up with something like this (for gradle but I guess you can figure out the maven equivalent):
```gradle
[...]
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath "io.spring.gradle:dependency-management-plugin:1.0.3.RELEASE"
    }
}
apply plugin: "io.spring.dependency-management"
[...]
dependencyManagement {
    imports {
        mavenBom 'com.amazonaws:aws-java-sdk-bom:1.11.228'
    }
}
dependencies {
[...]
    compile group: "com.j256.cloudwatchlogbackappender", name: "cloudwatchlogbackappender", version: "1.10"
    compile 'com.amazonaws:aws-java-sdk-cloudwatch'
    compile 'com.amazonaws:aws-java-sdk-ec2'
    compile 'com.amazonaws:aws-java-sdk-logs'
}
```

It would be nice to find something like this in the README.
Cheers

**Comment by j256** [comment]
This has been added to the main readme.  Thanks much.  See: https://github.com/j256/cloudwatch-logback-appender/commit/d855c1af20f240e48731d3ab3b3ddb5953cd20bd
