### ISSUE TITLE
Undocumented AWS SDK Dependencies

### ISSUE THREAD

**Issue by RedXi** [j256/cloudwatch-logback-appender#13]
It took me some time to figure out which AWS SDK dependencies are needed to use the library. The entire AWS SDK has about 80 MiB but it seems, the components aws-java-sdk-logs and aws-java-sdk-ec2 are sufficient. Maybe this should be added to the README.

**Comment by j256** [comment]
This has been added to the main docs.  Thanks much @RedXi .
