### ISSUE TITLE
Log stream patterns with ':' in them are not working

### ISSUE THREAD

**Issue by yemanasyan** [j256/cloudwatch-logback-appender#33]
This one is working: stream-%instance-%date{yyyyMMdd,UTC}-%uuid
This one is not working: stream-%date{yyyyMMdd,UTC}-%uuid
This one as well doesn't work: stream-%address-%date{yyyyMMdd,UTC}-%uuid

Is there a way to print the issues and see why it's not working when %instance is not specified?

**Comment by j256** [comment]
Thanks @yemanasyan.  Can you be more specific?  What does "not working" mean.  You mean that you don't see those log-streams in the console?

**Comment by yemanasyan** [comment]
@j256 I've tried to debug the code. I was wrong, the issue is not in the log appended, it's in my Cloudwatch Log stream policy naming validation. E.g. yyyy-MM-dd HH:mm:ss.UTC won't work because of the **:** symbol. I think that it would be a great feature to print the reason why the appended fails instead of failing silently.

**Comment by j256** [comment]
And you think my code is silently eating an exception?

**Comment by j256** [comment]
Certainly the code should reject formats with : if that is an invalid character.

**Comment by yemanasyan** [comment]
@j256 yes, the code just silently eats the exception. In my opinion, that would be great to at least print it or even exit the app.

**Comment by j256** [comment]
You can also use the [emergency appender](https://github.com/j256/cloudwatch-logback-appender#emergency-appender) right?  Have you RTFM?

**Comment by yemanasyan** [comment]
I've tried, didn't notice that it's there. Thank you for your time!!! I'll close the ticket.
