### ISSUE TITLE
should filter out invalid characters from log-stream names

### ISSUE THREAD

**Issue by j256** [j256/cloudwatch-logback-appender#34]
CloudWatch doesn't support log-streams with ':' in them maybe.  What other characters are not allowed?

**Comment by yemanasyan** [comment]
@j256 this is the CloudWatch Stream validation regex: **[^:*]***

This is the full message from AWS:
`1 validation error detected: Value 'something123,.;[]'/123`0-=:something else1456' at 'logStreamName' failed to satisfy constraint: Member must satisfy regular expression pattern: [^:*]*`
