### ISSUE TITLE
Instance credentials are temporary and expire after a few hours

### ISSUE THREAD

**Issue by alexfoxgill** [j256/cloudwatch-logback-appender#4]
EC2 instance credentials via the `DefaultAWSCredentialsProviderChain` are temporary and expire, throwing an exception and preventing any logs from being written: https://aws.amazon.com/premiumsupport/knowledge-center/security-token-expired/

Using a different constructor for AWS client should resolve the issue

**Comment by j256** [comment]
Oh interesting.  Shows my ignorance of that.  I've fixed but slightly different that your's.
