### ISSUE TITLE
How can i change the destination region? 

### ISSUE THREAD

**Issue by ZanonEdoardo** [j256/cloudwatch-logback-appender#8]
The env variable "AWS_REGION"->"eu-west-1" of deafultProvideChain not work. I will take every "us-east-1".

**Comment by j256** [comment]
Sorry, I don't understand.  Is there a problem with the AWS class or something in my code?

**Comment by RedXi** [comment]
For us it works. We configure the region in the logback.xml.

```html
<appender name="CLOUDWATCH" class="com.j256.cloudwatchlogbackappender.CloudWatchAppender">
    <region>eu-west-1</region>
    <!-- ... -->
</appender>
```

**Comment by j256** [comment]
I'm going to close this.  Thanks @RedXi .  Feel free to reopen @ZanonEdoardo .
