### ISSUE TITLE
Setting log Stream name as today's date and guid?

### ISSUE THREAD

**Issue by kdshinde** [j256/cloudwatch-logback-appender#9]
Could you please tell me how to set log stream name as a (today's date + guid) ?

**Comment by zoell** [comment]
+1, is this possible?

**Comment by AlvaroCaste** [comment]
yep, it would be helpful. Thanks

**Comment by AnatoliiStepaniuk** [comment]
which tokens are there except %instance ? for example for uuid or timestamp

**Comment by yamamotodin** [comment]
On fargate, %instance is not work. Its be "unknown".

**Comment by j256** [comment]
I've added support for using the layout to build the name of the logstream.  This means that %date is supported with patterns and timezone.   I've updated the README with the tokens that are supported.  I've also added support for %uuid, %hostName, %hostAddress, %systemProperty, and %systemEnviron layout patterns.

**Comment by j256** [comment]
> On fargate, %instance is not work. Its "unknown".

Please use a different issue in the future.  The instance tokens only work if running under EC2.  You can set the instance name using `Ec2InstanceNameConverter.setInstanceName(...)` if that helps.

**Comment by j256** [comment]
> Could you please tell me how to set log stream name as a (today's date + guid) ?

So with 2.0+ this would be something like:

	<logStream>stream-%date{yyyyMMdd-HHmmss.SSS}-%uuid</logStream>

This generated the following name for me:

	stream-20201229-191944.500-eb2d52a1-4b90-496b-8395-b3be1ff5d779

**Comment by j256** [comment]
> which tokens are there except %instance ? for example for uuid or timestamp

I've added more details to the README.
